CREATE DATABASE IF NOT EXISTS financial;
USE financial;

DROP TABLE IF EXISTS categories;
CREATE TABLE IF NOT EXISTS categories(
	id INT(10) UNSIGNED AUTO_INCREMENT NOT NULL,
	description VARCHAR(255) UNIQUE NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	PRIMARY KEY(id)
)ENGINE = InnoDB DEFAULT CHARSET = Latin1;

DROP TABLE IF EXISTS expenses;
CREATE TABLE IF NOT EXISTS expenses(
	id INT(10) UNSIGNED AUTO_INCREMENT NOT NULL,
	description VARCHAR(255) UNIQUE NOT NULL,
	category_id INT(10) UNSIGNED,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	PRIMARY KEY(id),
	CONSTRAINT fk_expense_categories_id
	FOREIGN KEY	(category_id) REFERENCES categories(id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
)ENGINE = InnoDB DEFAULT CHARSET = Latin1;